add_newline = false

[line_break]
disabled = true

[battery]
format = ''

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 25
style = "bold orange"

[[battery.display]]
threshold = 50
style ="bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[git_branch]
truncation_length = 20

[elm]
format = '$symbol'

[nodejs]
format = '$version $symbol'
